name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] # Ge√§ndert von main auf master

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # Hier sagen wir .NET, dass es im Unterordner suchen soll
      - name: Publish .NET Core Project
        run: dotnet publish GitHubWebsite/GitHubWebsite.csproj -c Release -o release

      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Create 404 page for routing
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Commit and Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages