name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish .NET Core Project
        run: dotnet publish GitHubWebsite/GitHubWebsite.csproj -c Release -o release /p:BlazorEnableCompression=false /p:PublishTrimmed=false

      # FEHLERSUCHE: Wir lassen uns im Log anzeigen, was im Ordner wirklich drin ist
      - name: Debug Folder Structure
        run: ls -R release/wwwroot/_framework

      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Create 404 page for routing
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # Wir nutzen hier eine alternative Einstellung, um sicherzustellen, 
      # dass wirklich ALLE Dateien (auch .json) mitgenommen werden.
      - name: Commit and Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
          clean: true
          single-commit: true
          git-config-name: GitHub Action
          git-config-email: action@github.com